"""Provider-onboarding DRAFT route-config builder + report (Issue: post-#14).

Turns SAFE inspection observations (no applicant data) into a DRAFT
``BrowserRouteConfig`` + a structured onboarding report. Drafts are never
verified automatically: ``last_verified_at`` stays None, the config lives in a
``drafts/`` directory (never the live dir), and the registry entry stays
``discovered`` until a human explicitly approves.
"""

from __future__ import annotations

import datetime as dt
import re
from typing import Optional
from urllib.parse import urlsplit

from ...models.browser.config import (
    AccessControlDetectionConfig,
    ActionBinding,
    BrowserActionSafety,
    BrowserFieldBinding,
    BrowserRouteConfig,
    CallbackDetectionConfig,
    MatchPattern,
    MatchStrategy,
    PageSignatureSpec,
    QuoteDetectionConfig,
    ValidationDetectionConfig,
)
from ...models.registry import MarketRegistryEntry
from .canonical import FieldMapping, map_label

_HTTPS_RE = re.compile(r"^https://", re.IGNORECASE)
_QUOTE_LINK_TOKENS = (
    "get a quote", "get quote", "auto quote", "start quote", "car insurance quote",
    "compare rates", "get started", "quote",
)


class OnboardingError(ValueError):
    """A deterministic onboarding failure (bad URL, missing draft, ...)."""


def validate_candidate_url(url: str) -> str:
    """Validate a candidate quote URL (HTTPS + non-empty host)."""
    candidate = (url or "").strip()
    if not _HTTPS_RE.match(candidate):
        raise OnboardingError("candidate quote URL must be HTTPS")
    parts = urlsplit(candidate)
    if not parts.netloc:
        raise OnboardingError("candidate quote URL has no host")
    return candidate


def derive_allowed_hosts(final_url: str, registry_id: str) -> list[str]:
    """Allowed hosts = the final URL's host (defense: never third-party)."""
    host = (urlsplit(final_url).netloc or "").lower()
    if not host:
        raise OnboardingError(f"could not derive a host from {final_url!r}")
    return [host]


def is_quote_link(text: str) -> bool:
    """Heuristic for same-provider 'start your quote' navigation candidates."""
    normalized = (text or "").lower()
    return any(token in normalized for token in _QUOTE_LINK_TOKENS)


def build_field_binding(mapping: FieldMapping, external_id: str) -> Optional[BrowserFieldBinding]:
    """One BrowserFieldBinding from a mapped field observation (no guessing)."""
    if not mapping.mapped or not mapping.canonical_path:
        return None
    strategy = MatchStrategy.NORMALIZED_LABEL
    return BrowserFieldBinding(
        external_field_id=external_id or mapping.label,
        match_patterns=[MatchPattern(strategy=strategy, value=mapping.label)],
        canonical_path=mapping.canonical_path,
        control_type=mapping.control_type,
        fill_strategy=mapping.fill_strategy,
        transform=mapping.transform,
        required=mapping.required,
        sensitivity=mapping.sensitivity,
        option_map=dict(mapping.option_map),
    )


def build_draft_config(
    registry: MarketRegistryEntry,
    *,
    start_url: str,
    allowed_hosts: list[str],
    heading: Optional[str],
    url_pattern: Optional[str],
    mapped_fields: list[FieldMapping],
    observed_buttons: list[str],
    access_control_detected: bool,
    callback_detected: bool,
    notes: Optional[str] = None,
    aggregator: bool = False,
) -> BrowserRouteConfig:
    """Deterministic DRAFT config from safe inspection observations."""
    signatures: list[PageSignatureSpec] = []
    if url_pattern:
        signatures.append(
            PageSignatureSpec(
                signature_id=f"{registry.registry_id}_landing",
                url_pattern=url_pattern,
                heading_patterns=[heading] if heading else [],
            )
        )

    bindings: list[BrowserFieldBinding] = []
    seen_paths: set[str] = set()
    for idx, mapping in enumerate(mapped_fields):
        binding = build_field_binding(mapping, external_id=f"{registry.registry_id}_f{idx}")
        if binding is None or binding.canonical_path in seen_paths:
            continue
        seen_paths.add(binding.canonical_path)
        bindings.append(binding)

    action_bindings: list[ActionBinding] = []
    continue_labels = [b for b in observed_buttons if "continue" in b.lower() or "next" in b.lower()]
    if continue_labels:
        action_bindings.append(
            ActionBinding(
                action_type="continue", safety=BrowserActionSafety.SAFE_NAVIGATION,
                label_patterns=continue_labels[:5],
            )
        )

    automation_notes = (
        f"DRAFT generated by provider onboarding on {dt.date.today().isoformat()}. "
        f"NOT verified - registry status is '{registry.status.value}'. Do NOT send any "
        "applicant data until a human approves and the route is verified. "
        "Inspection was SAFE (no PII). "
        f"barrier_detected={access_control_detected} callback_detected={callback_detected}"
    )
    if notes:
        automation_notes += f" notes={notes}"

    access_config = AccessControlDetectionConfig(
        patterns=["verify you are human", "security check", "automated access", "captcha",
                  "sorry, you have been blocked", "you have been blocked", "cloudflare",
                  "unusual traffic", "access denied"],
        iframe_src_patterns=["recaptcha", "hcaptcha", "challenges.cloudflare.com"],
        selectors=["[class*='g-recaptcha']", "[class*='h-captcha']", "iframe[src*='recaptcha']",
                   "iframe[src*='challenges.cloudflare.com']"],
    )
    return BrowserRouteConfig(
        registry_id=registry.registry_id,
        config_version=1,
        start_url=start_url,
        allowed_hosts=allowed_hosts,
        page_signatures=signatures,
        field_bindings=bindings,
        action_bindings=action_bindings,
        quote_detection=QuoteDetectionConfig(
            heading_patterns=["your quote", "your estimated premium", "quote results", "annual premium"],
            premium_label_patterns=["premium", "annual premium", "estimated annual premium", "price"],
            price_pattern=r"\$\s?([\d,]+(?:\.\d{1,2})?)",
            currency="CAD",
            reference_patterns=[r"(?:quote|reference|policy|application)[\s#]*([A-Z0-9]{4,})"],
            coverage_label_patterns=["third party liability", "accident benefits", "comprehensive", "collision"],
            firm_quote_patterns=["firm quote", "binding quote", "locked-in rate", "guaranteed for"],
        ),
        callback_detection=CallbackDetectionConfig(
            patterns=["call us", "complete by phone", "we will call you", "speak to a broker"],
        ),
        access_control_detection=access_config,
        validation_detection=ValidationDetectionConfig(
            patterns=["please enter", "please select", "must be between", "enter a valid", "this field is required"],
        ),
        automation_notes=automation_notes,
        last_verified_at=None,  # DRAFT - never auto-verified
    )


def build_report(
    registry: MarketRegistryEntry,
    *,
    start_url: str,
    final_url: str,
    allowed_hosts: list[str],
    heading: Optional[str],
    page_signature_ids: list[str],
    mapped_fields: list[FieldMapping],
    unmapped_fields: list[FieldMapping],
    observed_buttons: list[str],
    privacy_banner_detected: bool,
    access_control_detected: bool,
    callback_detected: bool,
    quote_detected: bool,
    draft_path: Optional[str],
    safe_to_live_test: bool = False,
    aggregator: bool = False,
    canonical_field_missing: list[str] | None = None,
    proposed_fields: list[dict] | None = None,
) -> dict:
    """Structured onboarding report (safe metadata only - no applicant data)."""
    return {
        "registry_id": registry.registry_id,
        "provider": registry.brand_or_program,
        "distribution_type": registry.distribution_type.value,
        "product_scope": registry.product_scope.value,
        "registry_status": registry.status.value,
        "candidate_quote_url": start_url,
        "final_url": final_url,
        "allowed_hosts": allowed_hosts,
        "page_heading": heading,
        "page_signatures": page_signature_ids,
        "mapped_fields": [
            {"label": m.label, "canonical_path": m.canonical_path,
             "control_type": m.control_type, "collection_length": m.collection_length}
            for m in mapped_fields
        ],
        "unmapped_fields": [{"label": m.label, "reason": m.reason} for m in unmapped_fields],
        "actions": observed_buttons[:20],
        "privacy_banner_detected": privacy_banner_detected,
        "access_control_detected": access_control_detected,
        "callback_required": callback_detected,
        "quote_detected": quote_detected,
        "aggregator_route": aggregator,
        "canonical_field_missing": canonical_field_missing or [],
        "proposed_fields": proposed_fields or [],
        "config_draft_path": draft_path,
        "verified": False,
        "safe_to_live_test": safe_to_live_test,
    }


def mark_unmapped_fields(unmapped: list[FieldMapping]) -> tuple[list[str], list[dict]]:
    """Report genuinely-new field labels as ``canonical_field_missing``."""
    missing = [m.label for m in unmapped if m.label and m.label.lower() not in ("", "optional")]
    proposed: list[dict] = []
    for m in unmapped[:10]:
        proposed.append({
            "observed_label": m.label,
            "control_type": m.control_type,
            "proposal": "localized intake catalog addition OR existing equivalent field",
        })
    return missing, proposed
